{
 "title": "RabbitMQ Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$instance\", job=\"Rabbit\"} "
    }
   ]
  },
  {
   "title": "Messages Rates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "sum by (job)  (irate(rabbitmq_queue_messages_published_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "Messages Published"
    },
    {
     "expr": "sum by (job)  (irate(rabbitmq_queue_messages_delivered_total{instance=\"$instance\"}[5m]) + irate(rabbitmq_queue_messages_delivered_no_ack_total{instance=\"$instance\"}[5m]) + irate(rabbitmq_queue_messages_get_total{instance=\"$instance\"}[5m])  + irate(rabbitmq_queue_messages_get_no_ack_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "Messages delivered"
    }
   ]
  },
  {
   "title": "Default VHost stat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_connections{instance=\"$instance\"}",
     "legendFormat": "Connections"
    },
    {
     "expr": "rabbitmq_channels{instance=\"$instance\"}",
     "legendFormat": "Channels"
    },
    {
     "expr": "rabbitmq_consumers{instance=\"$instance\"}",
     "legendFormat": "Consumers"
    },
    {
     "expr": "rabbitmq_exchanges{instance=\"$instance\"}",
     "legendFormat": "Exchanges"
    },
    {
     "expr": "rabbitmq_queues{instance=\"$instance\"}",
     "legendFormat": "Queues"
    }
   ]
  },
  {
   "title": "Erlang VM IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_bytes_output_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Output Bytes"
    },
    {
     "expr": "irate(erlang_vm_statistics_bytes_received_total{instance=\"$instance\"}[5m])",
     "legendFormat": "Received Bytes"
    }
   ]
  },
  {
   "title": "Erlang VM GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_garbage_collection_number_of_gcs{instance=\"$instance\"}[5m])",
     "legendFormat": "Number of GCs"
    },
    {
     "expr": "irate(erlang_vm_statistics_garbage_collection_words_reclaimed{instance=\"$instance\"}[5m])",
     "legendFormat": "Words Reclaimed"
    }
   ]
  },
  {
   "title": "Erlang VM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "erlang_vm_memory_bytes_total{instance=\"$instance\",kind=\"processes\"}",
     "legendFormat": "Processes Memory"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$instance\", usage=\"atom\"}",
     "legendFormat": "Atoms"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$instance\", usage=\"binary\"}",
     "legendFormat": "Binary"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$instance\",usage=\"code\"}",
     "legendFormat": "Code"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$instance\",usage=\"ets\"}",
     "legendFormat": "ETS"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$instance\",job=\"Rabbit\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\", job=\"Rabbit\"}",
     "legendFormat": "Resident Memory"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\",job=\"Rabbit\"}",
     "legendFormat": "Open FDs"
    },
    {
     "expr": "process_max_fds{instance=\"$instance\",job=\"Rabbit\"}",
     "legendFormat": "Max FDs"
    }
   ]
  },
  {
   "title": "Native Threads & CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "process_threads_total{instance=\"$instance\",job=\"Rabbit\"}",
     "legendFormat": "Threads"
    },
    {
     "expr": "sum(irate(process_cpu_seconds_total{instance=\"$instance\",job=\"Rabbit\"}[30s])) without (kind) * 100",
     "legendFormat": "CPU"
    }
   ]
  }
 ]
}